version: "3"
services:
  go-link-shortener-backend:
    build: ./go-link-shortener-backend
    environment:
      SERVER_STATIC_PATH: /var/www/go-link-shortener-backend
      CACHE_ADDRESS: redis:6379
      STORAGE_ADDRESS: mongodb://mongo:27017
      COUNTER_ADDRESS: etcd:2379
    ports:
      - 8080:8080
    volumes:
      - ./go-link-shortener-backend/static:/var/www/go-link-shortener-backend
    command:
      - /usr/local/bin/wait-for-it.sh
      - redis:6379
      - --
      - /usr/local/bin/wait-for-it.sh
      - mongo:27017
      - --
      - /usr/local/bin/wait-for-it.sh
      - etcd:2379
      - --
      - /usr/local/bin/go-link-shortener-backend

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - 9091:8081

  mongo:
    image: mongo:4-bionic
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 9092:8081

  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.3
    entrypoint: /usr/local/bin/etcd
    command:
      - "--listen-peer-urls=http://0.0.0.0:2380"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--initial-cluster=default=http://etcd:2380"
      - "--initial-advertise-peer-urls=http://etcd:2380"
      - "--advertise-client-urls=http://etcd:2379"
    ports:
      - 2379:2379 # for client requests
      - 2380:2380 # for peer communication

  e3w:
    image: soyking/e3w:0.1.0
    environment:
      GIN_MODE: release
    volumes:
      - ./go-link-shortener-backend/tools/e3w_config.ini:/app/conf/config.default.ini
    ports:
      - 9093:8080

  swagger:
    image: swaggerapi/swagger-ui:v3.24.0
    environment:
      SWAGGER_JSON: /etc/go-link-shortener-backend/swagger.json
    ports:
      - 9090:8080
    volumes:
      - ./go-link-shortener-backend/docs:/etc/go-link-shortener-backend
